DISTNAME=	kiko-0.4.4
PKGNAME=	kiko-0.4.4

CATEGORIES=	sysutils

MAINTAINER=	Hermes J. Rodríguez Azuaje <hejeroaz@gmail.com>
HOMEPAGE=	https://github.com/hrodrig/kiko
COMMENT=	Privacy-first web analytics collector

ONLY_FOR_ARCHS=	amd64 arm64 aarch64

NO_BUILD=	Yes
NO_TEST=	Yes
PKG_ARCH=	*

MASTER_SITES=	https://github.com/hrodrig/kiko/releases/download/v0.1.0/
DISTFILES=	kiko_0.1.0_openbsd_amd64.tar.gz

.include <bsd.port.mk>
